# Generated by Django 4.2.16 on 2026-04-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('skill_tags', models.CharField(help_text='Comma separated skills', max_length=255)),
                ('avg_resolution_time', models.FloatField(default=0.0)),
                ('current_load', models.IntegerField(default=0)),
                ('availability_status', models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy'), ('On Leave', 'On Leave')], default='Available', max_length=20)),
            ],
        ),
    ]
